/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "scratchpad_memory.sv:4.1-224.10" *)
module scratchpad_memory(clk, rw_, cs, rst, wr_addr, data_in, data_out);
  (* src = "scratchpad_memory.sv:108.5-112.8" *)
  wire [31:0] _000_;
  (* src = "scratchpad_memory.sv:108.5-112.8" *)
  wire [31:0] _001_;
  (* src = "scratchpad_memory.sv:108.5-112.8" *)
  wire [31:0] _002_;
  (* src = "scratchpad_memory.sv:114.5-140.8" *)
  wire [31:0] _003_;
  (* src = "scratchpad_memory.sv:0.0-0.0" *)
  wire [2:0] _004_;
  (* src = "scratchpad_memory.sv:0.0-0.0" *)
  wire [2:0] _005_;
  (* src = "scratchpad_memory.sv:0.0-0.0" *)
  wire [2:0] _006_;
  (* src = "scratchpad_memory.sv:0.0-0.0" *)
  wire [31:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  (* src = "scratchpad_memory.sv:110.22-110.36" *)
  wire [31:0] _168_;
  (* src = "scratchpad_memory.sv:109.13-109.42" *)
  wire _169_;
  wire [31:0] _170_;
  wire [31:0] _171_;
  wire [31:0] _172_;
  wire [31:0] _173_;
  wire [31:0] _174_;
  wire [31:0] _175_;
  wire [31:0] _176_;
  wire [31:0] _177_;
  wire [31:0] _178_;
  wire [31:0] _179_;
  wire [31:0] _180_;
  wire [31:0] _181_;
  wire [31:0] _182_;
  wire [31:0] _183_;
  wire [31:0] _184_;
  wire [31:0] _185_;
  wire [31:0] _186_;
  wire [31:0] _187_;
  wire [31:0] _188_;
  wire [31:0] _189_;
  wire [31:0] _190_;
  wire [31:0] _191_;
  wire [31:0] _192_;
  wire [31:0] _193_;
  wire [31:0] _194_;
  wire [31:0] _195_;
  wire [31:0] _196_;
  wire [31:0] _197_;
  wire [31:0] _198_;
  wire [31:0] _199_;
  wire [31:0] _200_;
  wire [31:0] _201_;
  wire [31:0] _202_;
  wire [31:0] _203_;
  wire [31:0] _204_;
  wire [31:0] _205_;
  wire [31:0] _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  (* src = "scratchpad_memory.sv:124.33-124.39" *)
  wire [31:0] _232_;
  (* src = "scratchpad_memory.sv:110.40-110.54" *)
  wire [31:0] _233_;
  (* src = "scratchpad_memory.sv:0.0-0.0" *)
  wire [31:0] _234_;
  wire [31:0] _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  (* src = "scratchpad_memory.sv:0.0-0.0" *)
  wire [31:0] _239_;
  (* src = "scratchpad_memory.sv:0.0-0.0" *)
  wire [31:0] _240_;
  (* src = "scratchpad_memory.sv:12.18-12.21" *)
  input clk;
  wire clk;
  (* src = "scratchpad_memory.sv:14.18-14.20" *)
  input cs;
  wire cs;
  (* src = "scratchpad_memory.sv:19.35-19.42" *)
  input [31:0] data_in;
  wire [31:0] data_in;
  (* src = "scratchpad_memory.sv:21.35-21.43" *)
  output [31:0] data_out;
  reg [31:0] data_out;
  (* src = "scratchpad_memory.sv:35.28-35.37" *)
  reg [2:0] fsm_state;
  reg [31:0] \memory[0] ;
  reg [31:0] \memory[10] ;
  reg [31:0] \memory[11] ;
  reg [31:0] \memory[12] ;
  reg [31:0] \memory[13] ;
  reg [31:0] \memory[14] ;
  reg [31:0] \memory[15] ;
  reg [31:0] \memory[16] ;
  reg [31:0] \memory[17] ;
  reg [31:0] \memory[18] ;
  reg [31:0] \memory[19] ;
  reg [31:0] \memory[1] ;
  reg [31:0] \memory[20] ;
  reg [31:0] \memory[21] ;
  reg [31:0] \memory[22] ;
  reg [31:0] \memory[23] ;
  reg [31:0] \memory[24] ;
  reg [31:0] \memory[2] ;
  reg [31:0] \memory[3] ;
  reg [31:0] \memory[4] ;
  reg [31:0] \memory[5] ;
  reg [31:0] \memory[6] ;
  reg [31:0] \memory[7] ;
  reg [31:0] \memory[8] ;
  reg [31:0] \memory[9] ;
  (* src = "scratchpad_memory.sv:36.28-36.42" *)
  wire [2:0] next_fsm_state;
  (* src = "scratchpad_memory.sv:15.18-15.21" *)
  input rst;
  wire rst;
  (* src = "scratchpad_memory.sv:13.18-13.21" *)
  input rw_;
  wire rw_;
  (* src = "scratchpad_memory.sv:17.36-17.43" *)
  input [4:0] wr_addr;
  wire [4:0] wr_addr;
  assign _007_ = _234_ + (* src = "scratchpad_memory.sv:0.0-0.0" *) _240_;
  (* \always_ff  = 32'd1 *)
  (* src = "scratchpad_memory.sv:114.5-140.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) data_out <= 32'd0;
    else if (_008_) data_out <= _003_;
  always @(posedge clk)
    if (_231_) \memory[9]  <= _001_;
  always @(posedge clk)
    if (_230_) \memory[8]  <= _001_;
  always @(posedge clk)
    if (_229_) \memory[7]  <= _001_;
  always @(posedge clk)
    if (_228_) \memory[6]  <= _001_;
  always @(posedge clk)
    if (_227_) \memory[5]  <= _001_;
  always @(posedge clk)
    if (_226_) \memory[4]  <= _001_;
  always @(posedge clk)
    if (_225_) \memory[3]  <= _001_;
  always @(posedge clk)
    if (_224_) \memory[2]  <= _001_;
  always @(posedge clk)
    if (_223_) \memory[24]  <= _001_;
  always @(posedge clk)
    if (_222_) \memory[23]  <= _001_;
  always @(posedge clk)
    if (_221_) \memory[22]  <= _001_;
  always @(posedge clk)
    if (_220_) \memory[21]  <= _001_;
  always @(posedge clk)
    if (_219_) \memory[20]  <= _001_;
  always @(posedge clk)
    if (_218_) \memory[1]  <= _001_;
  always @(posedge clk)
    if (_217_) \memory[19]  <= _001_;
  always @(posedge clk)
    if (_216_) \memory[18]  <= _001_;
  always @(posedge clk)
    if (_215_) \memory[17]  <= _001_;
  always @(posedge clk)
    if (_214_) \memory[16]  <= _001_;
  always @(posedge clk)
    if (_213_) \memory[15]  <= _001_;
  always @(posedge clk)
    if (_212_) \memory[14]  <= _001_;
  always @(posedge clk)
    if (_211_) \memory[13]  <= _001_;
  always @(posedge clk)
    if (_210_) \memory[12]  <= _001_;
  always @(posedge clk)
    if (_209_) \memory[11]  <= _001_;
  always @(posedge clk)
    if (_208_) \memory[10]  <= _001_;
  always @(posedge clk)
    if (_207_) \memory[0]  <= _001_;
  assign _136_ = ~ _000_[0];
  assign _137_ = ~ _000_[1];
  assign _138_ = ~ _000_[2];
  assign _139_ = ~ _000_[3];
  assign _140_ = ~ _000_[4];
  assign _141_ = ~ _000_[5];
  assign _142_ = ~ _000_[6];
  assign _143_ = ~ _000_[7];
  assign _144_ = ~ _000_[8];
  assign _145_ = ~ _000_[9];
  assign _146_ = ~ _000_[10];
  assign _147_ = ~ _000_[11];
  assign _148_ = ~ _000_[12];
  assign _149_ = ~ _000_[13];
  assign _150_ = ~ _000_[14];
  assign _151_ = ~ _000_[15];
  assign _152_ = ~ _000_[16];
  assign _153_ = ~ _000_[17];
  assign _154_ = ~ _000_[18];
  assign _155_ = ~ _000_[19];
  assign _156_ = ~ _000_[20];
  assign _157_ = ~ _000_[21];
  assign _158_ = ~ _000_[22];
  assign _159_ = ~ _000_[23];
  assign _160_ = ~ _000_[24];
  assign _161_ = ~ _000_[25];
  assign _162_ = ~ _000_[26];
  assign _163_ = ~ _000_[27];
  assign _164_ = ~ _000_[28];
  assign _165_ = ~ _000_[29];
  assign _166_ = ~ _000_[30];
  assign _167_ = ~ _000_[31];
  assign _010_ = _136_ & _137_;
  assign _011_ = _138_ & _139_;
  assign _012_ = _010_ & _011_;
  assign _013_ = _140_ & _141_;
  assign _014_ = _142_ & _143_;
  assign _015_ = _013_ & _014_;
  assign _016_ = _012_ & _015_;
  assign _017_ = _144_ & _145_;
  assign _018_ = _146_ & _147_;
  assign _019_ = _017_ & _018_;
  assign _020_ = _148_ & _149_;
  assign _021_ = _150_ & _151_;
  assign _022_ = _020_ & _021_;
  assign _023_ = _019_ & _022_;
  assign _024_ = _016_ & _023_;
  assign _025_ = _152_ & _153_;
  assign _026_ = _154_ & _155_;
  assign _027_ = _025_ & _026_;
  assign _028_ = _156_ & _157_;
  assign _029_ = _158_ & _159_;
  assign _030_ = _028_ & _029_;
  assign _031_ = _027_ & _030_;
  assign _032_ = _160_ & _161_;
  assign _033_ = _162_ & _163_;
  assign _034_ = _032_ & _033_;
  assign _035_ = _164_ & _165_;
  assign _036_ = _166_ & _167_;
  assign _037_ = _035_ & _036_;
  assign _038_ = _034_ & _037_;
  assign _039_ = _031_ & _038_;
  assign _040_ = _024_ & _039_;
  assign _041_ = _000_[0] & _137_;
  assign _042_ = _041_ & _011_;
  assign _043_ = _042_ & _015_;
  assign _044_ = _043_ & _023_;
  assign _045_ = _044_ & _039_;
  assign _046_ = _136_ & _000_[1];
  assign _047_ = _046_ & _011_;
  assign _048_ = _047_ & _015_;
  assign _049_ = _048_ & _023_;
  assign _050_ = _049_ & _039_;
  assign _051_ = _000_[0] & _000_[1];
  assign _052_ = _051_ & _011_;
  assign _053_ = _052_ & _015_;
  assign _054_ = _053_ & _023_;
  assign _055_ = _054_ & _039_;
  assign _056_ = _000_[2] & _139_;
  assign _057_ = _010_ & _056_;
  assign _058_ = _057_ & _015_;
  assign _059_ = _058_ & _023_;
  assign _060_ = _059_ & _039_;
  assign _061_ = _041_ & _056_;
  assign _062_ = _061_ & _015_;
  assign _063_ = _062_ & _023_;
  assign _064_ = _063_ & _039_;
  assign _065_ = _046_ & _056_;
  assign _066_ = _065_ & _015_;
  assign _067_ = _066_ & _023_;
  assign _068_ = _067_ & _039_;
  assign _069_ = _051_ & _056_;
  assign _070_ = _069_ & _015_;
  assign _071_ = _070_ & _023_;
  assign _072_ = _071_ & _039_;
  assign _073_ = _138_ & _000_[3];
  assign _074_ = _010_ & _073_;
  assign _075_ = _074_ & _015_;
  assign _076_ = _075_ & _023_;
  assign _077_ = _076_ & _039_;
  assign _078_ = _041_ & _073_;
  assign _079_ = _078_ & _015_;
  assign _080_ = _079_ & _023_;
  assign _081_ = _080_ & _039_;
  assign _082_ = _046_ & _073_;
  assign _083_ = _082_ & _015_;
  assign _084_ = _083_ & _023_;
  assign _085_ = _084_ & _039_;
  assign _086_ = _051_ & _073_;
  assign _087_ = _086_ & _015_;
  assign _088_ = _087_ & _023_;
  assign _089_ = _088_ & _039_;
  assign _090_ = _000_[2] & _000_[3];
  assign _091_ = _010_ & _090_;
  assign _092_ = _091_ & _015_;
  assign _093_ = _092_ & _023_;
  assign _094_ = _093_ & _039_;
  assign _095_ = _041_ & _090_;
  assign _096_ = _095_ & _015_;
  assign _097_ = _096_ & _023_;
  assign _098_ = _097_ & _039_;
  assign _099_ = _046_ & _090_;
  assign _100_ = _099_ & _015_;
  assign _101_ = _100_ & _023_;
  assign _102_ = _101_ & _039_;
  assign _103_ = _051_ & _090_;
  assign _104_ = _103_ & _015_;
  assign _105_ = _104_ & _023_;
  assign _106_ = _105_ & _039_;
  assign _107_ = _000_[4] & _141_;
  assign _108_ = _107_ & _014_;
  assign _109_ = _012_ & _108_;
  assign _110_ = _109_ & _023_;
  assign _111_ = _110_ & _039_;
  assign _112_ = _042_ & _108_;
  assign _113_ = _112_ & _023_;
  assign _114_ = _113_ & _039_;
  assign _115_ = _047_ & _108_;
  assign _116_ = _115_ & _023_;
  assign _117_ = _116_ & _039_;
  assign _118_ = _052_ & _108_;
  assign _119_ = _118_ & _023_;
  assign _120_ = _119_ & _039_;
  assign _121_ = _057_ & _108_;
  assign _122_ = _121_ & _023_;
  assign _123_ = _122_ & _039_;
  assign _124_ = _061_ & _108_;
  assign _125_ = _124_ & _023_;
  assign _126_ = _125_ & _039_;
  assign _127_ = _065_ & _108_;
  assign _128_ = _127_ & _023_;
  assign _129_ = _128_ & _039_;
  assign _130_ = _069_ & _108_;
  assign _131_ = _130_ & _023_;
  assign _132_ = _131_ & _039_;
  assign _133_ = _074_ & _108_;
  assign _134_ = _133_ & _023_;
  assign _135_ = _134_ & _039_;
  assign _008_ = { _236_, cs } != 2'h3;
  assign _009_ = | { _237_, _236_ };
  assign _168_ = wr_addr / (* src = "scratchpad_memory.sv:124.42-124.56" *) 32'd5;
  assign _169_ = next_fsm_state == (* src = "scratchpad_memory.sv:109.13-109.42" *) 3'h2;
  assign _232_ = _007_[4] ? _171_ : _170_;
  assign _170_ = _007_[3] ? _173_ : _172_;
  assign _171_ = _007_[3] ? _175_ : _174_;
  assign _172_ = _007_[2] ? _177_ : _176_;
  assign _173_ = _007_[2] ? _179_ : _178_;
  assign _174_ = _007_[2] ? _181_ : _180_;
  assign _175_ = _007_[2] ? _183_ : _182_;
  assign _176_ = _007_[1] ? _185_ : _184_;
  assign _177_ = _007_[1] ? _187_ : _186_;
  assign _178_ = _007_[1] ? _189_ : _188_;
  assign _179_ = _007_[1] ? _191_ : _190_;
  assign _180_ = _007_[1] ? _193_ : _192_;
  assign _181_ = _007_[1] ? _195_ : _194_;
  assign _182_ = _007_[1] ? _197_ : _196_;
  assign _183_ = _007_[1] ? _199_ : _198_;
  assign _184_ = _007_[0] ? \memory[1]  : \memory[0] ;
  assign _194_ = _007_[0] ? \memory[21]  : \memory[20] ;
  assign _195_ = _007_[0] ? \memory[23]  : \memory[22] ;
  assign _196_ = _007_[0] ? _200_ : \memory[24] ;
  assign _197_ = _007_[0] ? _202_ : _201_;
  assign _198_ = _007_[0] ? _204_ : _203_;
  assign _199_ = _007_[0] ? _206_ : _205_;
  assign _185_ = _007_[0] ? \memory[3]  : \memory[2] ;
  assign _186_ = _007_[0] ? \memory[5]  : \memory[4] ;
  assign _187_ = _007_[0] ? \memory[7]  : \memory[6] ;
  assign _188_ = _007_[0] ? \memory[9]  : \memory[8] ;
  assign _189_ = _007_[0] ? \memory[11]  : \memory[10] ;
  assign _190_ = _007_[0] ? \memory[13]  : \memory[12] ;
  assign _191_ = _007_[0] ? \memory[15]  : \memory[14] ;
  assign _192_ = _007_[0] ? \memory[17]  : \memory[16] ;
  assign _193_ = _007_[0] ? \memory[19]  : \memory[18] ;
  assign _207_ = _040_ & _002_[31];
  assign _208_ = _085_ & _002_[31];
  assign _209_ = _089_ & _002_[31];
  assign _210_ = _094_ & _002_[31];
  assign _211_ = _098_ & _002_[31];
  assign _212_ = _102_ & _002_[31];
  assign _213_ = _106_ & _002_[31];
  assign _214_ = _111_ & _002_[31];
  assign _215_ = _114_ & _002_[31];
  assign _216_ = _117_ & _002_[31];
  assign _217_ = _120_ & _002_[31];
  assign _218_ = _045_ & _002_[31];
  assign _219_ = _123_ & _002_[31];
  assign _220_ = _126_ & _002_[31];
  assign _221_ = _129_ & _002_[31];
  assign _222_ = _132_ & _002_[31];
  assign _223_ = _135_ & _002_[31];
  assign _224_ = _050_ & _002_[31];
  assign _225_ = _055_ & _002_[31];
  assign _226_ = _060_ & _002_[31];
  assign _227_ = _064_ & _002_[31];
  assign _228_ = _068_ & _002_[31];
  assign _229_ = _072_ & _002_[31];
  assign _230_ = _077_ & _002_[31];
  assign _231_ = _081_ & _002_[31];
  assign _233_ = wr_addr % (* src = "scratchpad_memory.sv:124.61-124.75" *) 32'd5;
  assign _234_ = _239_ * (* src = "scratchpad_memory.sv:0.0-0.0" *) 32'd5;
  (* \always_ff  = 32'd1 *)
  (* src = "scratchpad_memory.sv:48.5-60.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) fsm_state <= 3'h0;
    else fsm_state <= next_fsm_state;
  function [31:0] _489_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "scratchpad_memory.sv:0.0-0.0|scratchpad_memory.sv:122.13-138.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _489_ = b[31:0];
      2'b1?:
        _489_ = b[63:32];
      default:
        _489_ = a;
    endcase
  endfunction
  assign _235_ = _489_(32'd0, { _232_, 32'hxxxxxxxx }, { _237_, _236_ });
  assign _003_ = cs ? (* full_case = 32'd1 *) (* src = "scratchpad_memory.sv:118.18-118.21|scratchpad_memory.sv:118.14-139.12" *) _235_ : 32'd0;
  assign _002_[31] = _169_ ? (* full_case = 32'd1 *) (* src = "scratchpad_memory.sv:109.13-109.42|scratchpad_memory.sv:109.9-111.12" *) 1'h1 : 1'h0;
  assign _001_ = _169_ ? (* full_case = 32'd1 *) (* src = "scratchpad_memory.sv:109.13-109.42|scratchpad_memory.sv:109.9-111.12" *) data_in : 32'hxxxxxxxx;
  assign _000_ = _169_ ? (* full_case = 32'd1 *) (* src = "scratchpad_memory.sv:109.13-109.42|scratchpad_memory.sv:109.9-111.12" *) _007_ : 32'hxxxxxxxx;
  assign _006_ = rw_ ? (* full_case = 32'd1 *) (* src = "scratchpad_memory.sv:84.25-84.28|scratchpad_memory.sv:84.21-87.54" *) 3'h1 : 3'h2;
  assign _005_ = rw_ ? (* full_case = 32'd1 *) (* src = "scratchpad_memory.sv:77.25-77.29|scratchpad_memory.sv:77.21-80.54" *) 3'h0 : 3'h2;
  function [2:0] _496_;
    input [2:0] a;
    input [5:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "scratchpad_memory.sv:0.0-0.0|scratchpad_memory.sv:75.13-100.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _496_ = b[2:0];
      2'b1?:
        _496_ = b[5:3];
      default:
        _496_ = a;
    endcase
  endfunction
  assign _004_ = _496_(3'h0, { _005_, _006_ }, { _238_, _009_ });
  assign _236_ = fsm_state == (* full_case = 32'd1 *) (* src = "scratchpad_memory.sv:0.0-0.0|scratchpad_memory.sv:75.13-100.20" *) 3'h2;
  assign _237_ = fsm_state == (* full_case = 32'd1 *) (* src = "scratchpad_memory.sv:0.0-0.0|scratchpad_memory.sv:75.13-100.20" *) 3'h1;
  assign _238_ = ! (* full_case = 32'd1 *) (* src = "scratchpad_memory.sv:0.0-0.0|scratchpad_memory.sv:75.13-100.20" *) fsm_state;
  assign next_fsm_state = cs ? (* full_case = 32'd1 *) (* src = "scratchpad_memory.sv:71.13-71.16|scratchpad_memory.sv:71.9-101.12" *) _004_ : 3'h0;
  assign _239_ = 32'd4 - (* src = "scratchpad_memory.sv:0.0-0.0" *) _168_;
  assign _240_ = 32'd4 - (* src = "scratchpad_memory.sv:0.0-0.0" *) _233_;
  assign _002_[30:0] = { _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31] };
endmodule
